import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-slate-50 text-slate-900 antialiased`}
      >
        <div className="mx-auto flex min-h-screen w-full max-w-6xl flex-col px-6 py-8">
          <header className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
            <Link href="/" className="text-xl font-semibold tracking-tight">
              Mood Village
            </Link>
            <nav className="flex flex-wrap gap-3 text-sm font-medium">
              <Link className="rounded-full bg-white px-4 py-2 shadow-sm" href="/about">
                About
              </Link>
              <Link className="rounded-full bg-white px-4 py-2 shadow-sm" href="/village">
                Village
              </Link>
              <Link className="rounded-full bg-white px-4 py-2 shadow-sm" href="/events">
                Events
              </Link>
              <Link className="rounded-full bg-white px-4 py-2 shadow-sm" href="/progress">
                Progress
              </Link>
              <Link className="rounded-full bg-white px-4 py-2 shadow-sm" href="/profile">
                Profile
              </Link>
            </nav>
          </header>
          <main className="flex-1 py-10">{children}</main>
          <footer className="border-t border-slate-200 pt-6 text-xs text-slate-500">
            Built for the Mood Village hackathon.
          </footer>
        </div>
      </body>
    </html>
  );
}
